name: "Build ClockworkPi kernel (arm64)"
on:
  workflow_dispatch:
env:
  CACHIX_NAME: ${{ vars.CACHIX_NAME }}
jobs:
  build-kernel:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: ${{ env.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#packages.aarch64.linux-rpi5-clockworkpi \
              --accept-flake-config --print-build-logs
      - run: nix-shell --run "echo OK"